title: AVMPI Documentation
description: Documentation site for resources created for and by the Smithsonian's Audiovisual Media Preservation Initiative (AVMPI)
theme: just-the-docs

url: https://Smithsonian/avmpi-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
